/**
 * Cross-language test vectors: Go (libbitfs-go) vs TypeScript (libbitfs-ts).
 *
 * These tests load deterministic vectors generated by:
 *   go run ./cmd/testvectors/  (in libbitfs-go)
 *
 * Each test calls the corresponding TS function with the same inputs
 * and verifies that the output matches the Go output exactly.
 */

import { describe, it, expect } from 'vitest'
import { PrivateKey, PublicKey } from '@bsv/sdk'

import vectors from './vectors/go-vectors.json'

import { ecdh } from '../method42/ecdh.js'
import { computeKeyHash, deriveAESKey } from '../method42/kdf.js'
import { Wallet, seedFromMnemonic, MainNet, EXTERNAL_CHAIN } from '../wallet/index.js'
import { serializeChildEntry } from '../metanet/tlv.js'
import { NodeType } from '../metanet/types.js'
import type { ChildEntry } from '../metanet/types.js'
import { serializeRegistry } from '../revshare/serialize.js'
import type { RegistryState } from '../revshare/types.js'
import { doubleHash } from '../spv/merkle.js'

// ---------------------------------------------------------------------------
// Hex helpers (self-contained, no external dependency)
// ---------------------------------------------------------------------------

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2)
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16)
  }
  return bytes
}

function bytesToHex(data: Uint8Array): string {
  let hex = ''
  for (let i = 0; i < data.length; i++) {
    hex += data[i].toString(16).padStart(2, '0')
  }
  return hex
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('cross-language: method42', () => {
  it('ECDH shared secret matches Go output', () => {
    const v = vectors.method42_ecdh

    // Reconstruct key pair from hex
    const privKey = PrivateKey.fromString(v.privkey_hex, 'hex')
    const pubKey = PublicKey.fromString(v.pubkey_hex)

    const shared = ecdh(privKey, pubKey)
    expect(bytesToHex(shared)).toBe(v.shared_secret_hex)
  })

  it('deriveAESKey matches Go output', () => {
    const v = vectors.method42_derive_aes_key

    const sharedX = hexToBytes(v.shared_secret_hex)
    const keyHash = hexToBytes(v.key_hash_hex)

    const aesKey = deriveAESKey(sharedX, keyHash)
    expect(bytesToHex(aesKey)).toBe(v.aes_key_hex)
  })

  it('computeKeyHash matches Go output', () => {
    const v = vectors.method42_key_hash

    const plaintext = hexToBytes(v.plaintext_hex)
    const hash = computeKeyHash(plaintext)
    expect(bytesToHex(hash)).toBe(v.key_hash_hex)
  })
})

describe('cross-language: wallet', () => {
  it('deriveFeeKey(0,0) from known mnemonic matches Go output', () => {
    const v = vectors.wallet_derive

    const seed = seedFromMnemonic(v.mnemonic, '')
    expect(bytesToHex(seed)).toBe(v.seed_hex)

    const w = new Wallet(seed, MainNet)
    const feeKey = w.deriveFeeKey(EXTERNAL_CHAIN, 0)
    expect(feeKey.path).toBe(v.path)

    const pubHex = feeKey.publicKey.toDER('hex') as string
    expect(pubHex).toBe(v.pubkey_hex)
  })
})

describe('cross-language: metanet', () => {
  it('serializeChildEntry matches Go output', () => {
    const v = vectors.metanet_child_entry

    const entry: ChildEntry = {
      index: v.entry.index,
      name: v.entry.name,
      type: v.entry.type as NodeType,
      pubKey: hexToBytes(v.entry.pubkey_hex),
      hardened: v.entry.hardened,
    }

    const serialized = serializeChildEntry(entry)
    expect(bytesToHex(serialized)).toBe(v.serialized_hex)
  })
})

describe('cross-language: revshare', () => {
  it('serializeRegistry matches Go output', () => {
    const v = vectors.revshare_registry

    const state: RegistryState = {
      nodeID: hexToBytes(v.state.node_id_hex),
      totalShares: BigInt(v.state.total_shares),
      entries: v.state.entries.map(e => ({
        address: hexToBytes(e.address_hex),
        share: BigInt(e.share),
      })),
      modeFlags: v.state.mode_flags,
    }

    const serialized = serializeRegistry(state)
    expect(bytesToHex(serialized)).toBe(v.serialized_hex)
  })
})

describe('cross-language: spv', () => {
  it('doubleHash matches Go output', () => {
    const v = vectors.spv_double_hash

    const data = hexToBytes(v.data_hex)
    const hash = doubleHash(data)
    expect(bytesToHex(hash)).toBe(v.hash_hex)
  })
})
