// Copyright (c) 2024 The BitFS developers
// Use of this source code is governed by the Open BSV License v5
// that can be found in the LICENSE file.

// Package config provides configuration management for BitFS.
// Configuration uses a simple key=value file format with # comments.

import { homedir } from 'os'
import { join } from 'path'

import {
  ConfigNotFoundError,
  EmptyDataDirError,
  InvalidConfigLineError,
  InvalidListenAddrError,
  InvalidLogLevelError,
  InvalidNetworkError,
} from './errors.js'

/** BitFS configuration. */
export interface Config {
  /** Root data directory for BitFS. Default: ~/.bitfs */
  dataDir: string
  /** Address for the daemon HTTP server. Default: :8080 */
  listenAddr: string
  /** BSV network: "mainnet", "testnet", or "regtest". Default: mainnet */
  network: string
  /** Logging verbosity: "debug", "info", "warn", "error". Default: info */
  logLevel: string
  /** Path to the log file. Empty means stdout. Default: "" */
  logFile: string
}

// Valid networks.
const VALID_NETWORKS = new Set(['mainnet', 'testnet', 'regtest'])

// Valid log levels.
const VALID_LOG_LEVELS = new Set(['debug', 'info', 'warn', 'error'])

// Config key to field mapping (parse direction).
const KEY_TO_FIELD: Record<string, keyof Config> = {
  datadir: 'dataDir',
  listen: 'listenAddr',
  network: 'network',
  loglevel: 'logLevel',
  logfile: 'logFile',
}

// Field to config key mapping (serialize direction).
const FIELD_TO_KEY: Array<[keyof Config, string]> = [
  ['dataDir', 'datadir'],
  ['listenAddr', 'listen'],
  ['network', 'network'],
  ['logLevel', 'loglevel'],
  ['logFile', 'logfile'],
]

/**
 * Returns the default data directory path (~/.bitfs).
 * Falls back to ".bitfs" if the home directory cannot be determined.
 */
export function defaultDataDir(): string {
  try {
    return join(homedir(), '.bitfs')
  } catch {
    return '.bitfs'
  }
}

/** Returns a Config populated with sensible defaults. */
export function defaultConfig(): Config {
  return {
    dataDir: defaultDataDir(),
    listenAddr: ':8080',
    network: 'mainnet',
    logLevel: 'info',
    logFile: '',
  }
}

/**
 * Parse a key=value line.
 * Returns [key, value] on success, or null if the line is malformed.
 * Splits on the first '=' only; trims whitespace around key and value.
 */
function parseKeyValue(line: string): [string, string] | null {
  const idx = line.indexOf('=')
  if (idx < 0) return null

  const key = line.slice(0, idx).trim()
  const value = line.slice(idx + 1).trim()

  if (key === '') return null

  return [key, value]
}

/**
 * Sets a config field from a parsed key/value pair.
 * Unknown keys are silently ignored for forward compatibility.
 */
function setConfigField(cfg: Config, key: string, value: string): void {
  const field = KEY_TO_FIELD[key]
  if (field !== undefined) {
    cfg[field] = value
  }
  // Unknown keys silently ignored.
}

/**
 * Parse a key=value config string into a Config.
 *
 * Rules:
 * - Lines starting with # are comments (ignored)
 * - Empty lines are ignored
 * - Format: key=value (whitespace around = is trimmed)
 * - Unknown keys are silently ignored
 * - Lines without = are invalid and throw InvalidConfigLineError
 *
 * Unspecified fields retain defaults from defaultConfig().
 */
export function parseConfigString(content: string): Config {
  const cfg = defaultConfig()
  const lines = content.split('\n')

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()

    // Skip blank lines and comments.
    if (line === '' || line.startsWith('#')) {
      continue
    }

    const parsed = parseKeyValue(line)
    if (parsed === null) {
      throw new InvalidConfigLineError(i + 1, line)
    }

    setConfigField(cfg, parsed[0], parsed[1])
  }

  return cfg
}

/**
 * Serialize a Config to key=value format with header comments.
 * Output format matches the Go implementation: "key = value" with spaces around =.
 */
export function serializeConfig(cfg: Config): string {
  const lines: string[] = []
  lines.push('# BitFS Configuration')
  lines.push('# Generated by bitfs')
  lines.push('')

  for (const [field, key] of FIELD_TO_KEY) {
    lines.push(`${key} = ${cfg[field]}`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Validate host:port address format.
 * Accepts: ":8080", "127.0.0.1:80", "localhost:3000", "[::1]:8080".
 */
function validateAddr(addr: string): void {
  if (addr === '') {
    throw new InvalidListenAddrError('empty address')
  }

  // Handle IPv6 bracket notation: [::1]:8080
  if (addr.startsWith('[')) {
    const closeBracket = addr.indexOf(']')
    if (closeBracket < 0) {
      throw new InvalidListenAddrError('missing closing bracket for IPv6')
    }
    // After the closing bracket, must be :port
    const rest = addr.slice(closeBracket + 1)
    if (!rest.startsWith(':') || rest.length < 2) {
      throw new InvalidListenAddrError('missing port after IPv6 address')
    }
    const port = rest.slice(1)
    if (port === '' || !/^\d+$/.test(port)) {
      throw new InvalidListenAddrError(`invalid port: ${port}`)
    }
    return
  }

  // Find the last colon — this separates host from port.
  const lastColon = addr.lastIndexOf(':')
  if (lastColon < 0) {
    throw new InvalidListenAddrError('missing port in address')
  }

  const port = addr.slice(lastColon + 1)
  if (port === '') {
    throw new InvalidListenAddrError('missing port in address')
  }
  if (!/^\d+$/.test(port)) {
    throw new InvalidListenAddrError(`invalid port: ${port}`)
  }
}

/**
 * Validate that all configuration values are within acceptable ranges.
 * Throws the first error encountered.
 */
export function validateConfig(cfg: Config): void {
  if (cfg.dataDir === '') {
    throw new EmptyDataDirError()
  }

  if (!VALID_NETWORKS.has(cfg.network)) {
    throw new InvalidNetworkError()
  }

  validateAddr(cfg.listenAddr)

  if (!VALID_LOG_LEVELS.has(cfg.logLevel.toLowerCase())) {
    throw new InvalidLogLevelError()
  }
}

/**
 * Load a configuration file from disk.
 * Uses Node.js fs/promises. Browser users should use parseConfigString instead.
 *
 * Any keys not present in the file retain their default values.
 */
export async function loadConfig(path: string): Promise<Config> {
  const { readFile } = await import('fs/promises')

  let content: string
  try {
    content = await readFile(path, 'utf-8')
  } catch (err: unknown) {
    if (isNodeError(err) && err.code === 'ENOENT') {
      throw new ConfigNotFoundError()
    }
    throw err
  }

  return parseConfigString(content)
}

/**
 * Save a configuration file to disk.
 * Creates parent directories if needed. File permissions: 0o600.
 * Uses Node.js fs/promises. Browser users should use serializeConfig instead.
 */
export async function saveConfig(path: string, cfg: Config): Promise<void> {
  const { writeFile, mkdir } = await import('fs/promises')
  const { dirname } = await import('path')

  const dir = dirname(path)
  await mkdir(dir, { recursive: true, mode: 0o700 })

  const content = serializeConfig(cfg)
  await writeFile(path, content, { mode: 0o600 })
}

/** Returns the path to the config file within the data directory. */
export function configPath(dataDir: string): string {
  return join(dataDir, 'config')
}

/** Type guard for Node.js system errors with a code property. */
function isNodeError(err: unknown): err is NodeJS.ErrnoException {
  return err instanceof Error && 'code' in err
}
